# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [16]:
# Your code goes here
import pandas as pd
import numpy as np
# Import new data
url0 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

insurance_part0 = pd.read_csv(url0)
insurance_part1 = pd.read_csv(url1)
insurance_part2 = pd.read_csv(url2)

from cleaning import mr_clean

print(len(insurance.columns.tolist()))

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

13

In [29]:
insurance_part1 = insurance_part1.loc[ : , ["Customer",
                                            "ST",
                                            "GENDER",
                                            "Education",
                                            "Customer Lifetime Value",
                                            "Income",
                                            "Monthly Premium Auto",
                                            "Number of Open Complaints",
                                            "Policy Type",
                                            "Vehicle Class",
                                            "Total Claim Amount"]
    ]
insurance_part2 = insurance_part2.loc[ : , ["Customer",
                                            "State",
                                            "Gender",
                                            "Education",
                                            "Customer Lifetime Value",
                                            "Income",
                                            "Monthly Premium Auto",
                                            "Number of Open Complaints",
                                            "Policy Type",
                                            "Vehicle Class",
                                            "Total Claim Amount"
                                           ]
    ]

cleaned0 = mr_clean(insurance_part0)
cleaned1 = mr_clean(insurance_part1)
cleaned2 = mr_clean(insurance_part2)

display(cleaned0.head())
display(cleaned1.head())
display(cleaned2.head())

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Request from customer,Master,588174.235,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.590,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.170,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.180,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.650,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,GS98873,Arizona,F,Bachelor,323912.47,16061,88,0,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11,79487,114,0,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02,54230,112,0,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30,71210,214,1,Personal Auto,Luxury,1027.2
4,WH52799,Arizona,F,College,380812.21,94903,94,0,Corporate Auto,Two-Door Car,451.2

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,SA25987,Washington,M,High School or Below,3479.137523,0,104,0,Personal Auto,Two-Door Car,499.200000
1,TB86706,Arizona,M,Master,2502.637401,0,66,0,Personal Auto,Two-Door Car,3.468912
2,ZL73902,Nevada,F,Bachelor,3265.156348,25820,82,0,Personal Auto,Four-Door Car,393.600000
3,KX23516,California,F,High School or Below,4455.843406,0,121,0,Personal Auto,SUV,699.615192
4,FN77294,California,M,High School or Below,7704.958480,30366,101,2,Personal Auto,SUV,484.800000

In [11]:
%load_ext autoreload
%autoreload 2

In [30]:
cleaned_insurance = pd.concat([cleaned0, cleaned1, cleaned2], axis=0, ignore_index=True)
display(cleaned_insurance)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Request from customer,Master,5.881742e+05,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,6.979536e+05,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1.288743e+06,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7.645862e+05,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5.363077e+05,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,M,Bachelor,2.340599e+04,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,F,College,3.096511e+03,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,M,Bachelor,8.163890e+03,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,M,College,7.524442e+03,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,M,College,2.611837e+03,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [45]:
# Your code goes here
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

marketing_data = pd.read_csv(url3)

display(marketing_data.head(10))

#TASK 1:create a summary table showing total revenue for each sales channel (branch, call center, web, and mail). 

revenue_channel = marketing_data.pivot_table(
    index = "sales_channel",
    values = "monthly_premium_auto",
    aggfunc = "sum"
)
display(revenue_channel.round(2))

marketing_data.columns.tolist()

# AGENTS HAVE THE HIGHEST REVENUE / MONTHLY PREMIUMS

#TASK 2: Create a pivot table that shows the average customer lifetime value per gender and education level. 

ltv_analysis = marketing_data.pivot_table(
    index = "education",
    columns = "gender",
    values = "customer_lifetime_value",
    aggfunc = "mean"
)
display(ltv_analysis.round(2))

# MEN HAVE A HIGHER LIFT TIME VALUE PER COHORT, EXCEPT FOR HIGH SCHOOL WOMAN. HIGH SCHOOL WOMEN HAVE THE HIGHEST LTV.

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
5,5,HO81102,California,4745.181764,No,Basic,High School or Below,2011-02-14,Employed,M,...,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A,2
6,6,IW72280,California,5035.035257,No,Basic,Doctor,2011-02-14,Employed,F,...,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,A,2
7,7,IH64929,California,4956.247235,No,Basic,High School or Below,2011-02-24,Employed,M,...,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,A,2
8,8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,A,1
9,9,QX31376,Oregon,17114.328150,No,Extended,Master,2011-01-04,Employed,F,...,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,A,1

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

gender                      F        M
education
Bachelor              7874.27  7703.60
College               7748.82  8052.46
Doctor                7328.51  7415.33
High School or Below  8675.22  8149.69
Master                8157.05  8168.83

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [63]:
# Your code goes here
# TASK 3: Create a summary table showing the number of complaints by policy type and month. Show it in a long format table.
complaint_analysis = marketing_data.pivot_table(
    index = "policy_type",
    columns = "month",
    values = "number_of_open_complaints",
    aggfunc = "sum"
)

complaint_analysis = complaint_analysis.reset_index()

display(complaint_analysis.round(2))

complaint_longtable = pd.melt(
    complaint_analysis,
    id_vars = "policy_type",
    value_vars = [1, 2],
    var_name = "month",
    value_name = "complaints"
)

display(complaint_analysis.round(2))

complaint_analysis.columns.tolist()

month     policy_type        1        2
0      Corporate Auto   443.43   385.21
1       Personal Auto  1727.61  1453.68
2        Special Auto    87.07    95.23

month     policy_type        1        2
0      Corporate Auto   443.43   385.21
1       Personal Auto  1727.61  1453.68
2        Special Auto    87.07    95.23

['policy_type', 1, 2]